spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_talk?useSsl=false&serverTimezone=UTC
    username: min
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#        default_batch_fetch_size: 500